</TD>
          <TD background=<%=AppConstants.NNT_APP_CONTEXT_ROOT%>/styles/images/B5.jpg>&nbsp;</TD></TR>
        <TR>
          <TD><IMG src="<%=AppConstants.NNT_APP_CONTEXT_ROOT%>/styles/images/B6.jpg" width=35 height=16></TD>
          <TD background=<%=AppConstants.NNT_APP_CONTEXT_ROOT%>/styles/images/B77.jpg>
            <DIV align=right><IMG src="<%=AppConstants.NNT_APP_CONTEXT_ROOT%>/styles/images/B7.jpg" width=663 
            height=16></DIV></TD>
          <TD><IMG src="<%=AppConstants.NNT_APP_CONTEXT_ROOT%>/styles/images/b8.jpg" width=12 
        height=16></TD></TR></TBODY></TABLE><BR></TD></TR></TBODY></TABLE>
<SCRIPT type=text/javascript src=""></SCRIPT>

<TABLE border=0 cellSpacing=0 cellPadding=0 width=985 align=center>
  <TBODY>
  <TR>
    <TD height=41 background=<%=AppConstants.NNT_APP_CONTEXT_ROOT%>/styles/images/footer.jpg>
      <TABLE border=0 cellSpacing=0 cellPadding=0 width="98%" align=center>
        <TBODY>
        <TR>
          <TD vAlign=top align=left>B&#7843;n quy&#7873;n thu&#7897;c v&#7873; Kho B&#7841;c Nh&#224; n&#432;&#7899;c Vi&#7879;t 
            Nam <BR>Phi&#234;n b&#7843;n 2.2.4 &nbsp;&nbsp;&nbsp;N&#259;m 2015 </TD>
          <TD align=right>&#272;&#7883;a ch&#7881;: 32 C&#225;t Linh, Qu&#7853;n &#272;&#7889;ng &#272;a, H&#224; N&#7897;i, Vi&#7879;t Nam 
            <BR>&#272;i&#7879;n tho&#7841;i: (04)62764300 Fax: (04)62764367 &#8211; (04)62764368 </TD>
          <TD vAlign=top align=left></TD>
          <TD vAlign=top 
align=right></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></BODY></HTML>